# fly.toml app configuration file generated for physician-assistant-srck5q on 2026-07-15T06:08:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'physician-assistant-srck5q'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/.venv/bin/alembic upgrade head"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '30s'
    interval = '15s'
    method = 'GET'
    path = '/docs'
    timeout = '5s'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
